"""added column to Post for schedule week

Revision ID: 096365457e2e
Revises: 8ae74860cf23
Create Date: 2025-11-03 15:13:50.254103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096365457e2e'
down_revision = '8ae74860cf23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_week', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('schedule_week')

    # ### end Alembic commands ###
