"""added PTO column to time off requests

Revision ID: 269ab7335681
Revises: 
Create Date: 2025-12-19 10:26:34.335969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269ab7335681'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_off_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pto', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_off_requests', schema=None) as batch_op:
        batch_op.drop_column('is_pto')

    # ### end Alembic commands ###
