"""added review model

Revision ID: eebd4aff8adb
Revises: 096365457e2e
Create Date: 2025-11-13 15:20:48.095371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebd4aff8adb'
down_revision = '096365457e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('appliance', sa.String(length=100), nullable=True),
    sa.Column('sales_associate', sa.String(length=50), nullable=True),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
